# Generated by Django 5.0.3 on 2024-07-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
